version: 1
default_environment: dev
project_id: 6d8afb1b-9a15-4429-934c-93356376925a
environments:
  - name: dev
  - name: staging
  - name: prod

plugins:
  extractors:
    - name: tap-postgres
      variant: meltanolabs
      pip_url: git+https://github.com/MeltanoLabs/tap-postgres.git
      config:
        database: northwind
        default_replication_method: FULL_TABLE
        user: postgres
        host: db 
        password: thewindisblowing
        filter_schemas:
          - public

    - name: tap-csv
      variant: meltanolabs
      pip_url: git+https://github.com/MeltanoLabs/tap-csv.git

    - name: tap-csv-initial
      inherit_from: tap-csv
      config:
        files:
          - entity: order_details
            path: /code-challenge/data/order_details.csv
            keys:
              - order_id

    - name: tap-csv-current
      inherit_from: tap-csv
      config:
        csv_files_definition: /code-challenge/data/data-pipeline/current_data/.temp/files_definition.json

  loaders:
    - name: target-postgres
      variant: meltanolabs
      pip_url: meltanolabs-target-postgres
      config:
        dbname: new_northwind
        host: db-2
        port: 5433 
        user: postgres
        password: thewindisblowing
        default_target_schema: raw

utilities:
  - name: organize-files
    namespace: organize-files
    commands:
      organize_csv:
        args: script/organize_csv.py
        executable: python

  - name: organize_current_data
    namespace: organize_current_data
    commands:
      organize_data:
        args: script/current_data.py
        executable: python

  - name: files_definition
    namespace: files_definition
    commands:
      file_definition:
        args: script/files_definition.py
        executable: python

  - name: airflow
    variant: apache
    pip_url: git+https://github.com/meltano/airflow-ext.git@main
    constraints:
      - https://raw.githubusercontent.com/apache/airflow/constraints-2.8.1/constraints-no-providers-${MELTANO__PYTHON_VERSION}.txt

jobs:
  - name: input-local
    tasks:
      - tap-postgres target-csv
      - tap-csv-initial target-csv
      - organize-files: organize_csv

  - name: input-postgres
    tasks:
      - organize_current_data: organize_data
      - files_definition: file_definition
      - tap-csv-current target-postgres

schedules:
  - name: pipeline-part1
    interval: '@daily'
    job: input-local

  - name: pipeline-part2
    interval: '@daily'
    job: input-postgres
